[package]
name = "affection_switches"
version = "0.1.0"
edition = "2021"

[dependencies]
emotion_detection = { path = "../emotion_detection" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
regex = "1.10"
